apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/argoproj/argo-cd.git
      revision: HEAD
      files:
      - path: "applicationset/examples/git-generator-files-discovery/cluster-config/**/config.json"
      values:
        repoURL: https://github.com/argoproj/argo-cd.git
        revision: HEAD
  template:
    metadata:
      name: '{{.cluster.name}}-guestbook'
    spec:
      info:
        - name: "parameters"
          value: |
            {{ toPrettyJson . }}
      project: default
      source:
        repoURL: "{{.values.repoURL}}"
        targetRevision: "{{.values.revision}}"
        path: "applicationset/examples/git-generator-files-discovery/apps/guestbook"
      destination:
        server: '{{.cluster.address}}'
        namespace: guestbook
